In [3]:
import numpy as np 


In [8]:
a = np.array([8,6,5])
print(a)

[8 6 5]


In [9]:
b = np.array([[6,7,8],[2,3,4]])
b

array([[6, 7, 8],
       [2, 3, 4]])

In [76]:
c = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
c.shape
   #shape use to know the matrix (4,3) or (3,3)m=

(4, 3)

In [75]:
c.reshape(6,2)

array([[ 30, 202],
       [303,   9],
       [404, 505],
       [ 11,  50],
       [ 17,  19],
       [ 60,   8]])

In [57]:
c[0,:]=[30,40,80]

In [58]:
print(c)

[[30 40 80]
 [ 9  3  5]
 [11 15 17]
 [19 31  8]]


In [59]:
c[0:,-2]=[30,40,50,60]
print(c)

[[30 30 80]
 [ 9 40  5]
 [11 50 17]
 [19 60  8]]


In [61]:
np.append(c,[[1,1,1]],axis=0)  #add new row

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11,  50,  17],
       [ 19,  60,   8],
       [  1,   1,   1]])

In [71]:
np.append(c,[[1],[1],[1],[1]],axis=1)

array([[ 30, 202, 303,   1],
       [  9, 404, 505,   1],
       [ 11,  50,  17,   1],
       [ 19,  60,   8,   1]])

In [74]:
np.delete(c,0,axis=0)


array([[  9, 404, 505],
       [ 11,  50,  17],
       [ 19,  60,   8]])

In [73]:
c[:2,1:] = [[202,303],[404,505]]


In [49]:
print(c+5)

[[ 8 13  9]
 [14  8 10]
 [16 20 22]
 [24 36 13]]


In [52]:
c[0]

0

In [19]:
c[1,0:3:1]        #slicing 

array([9, 3, 5])

In [32]:
print(c[:,-1:])

[[ 4]
 [ 5]
 [17]
 [ 8]]


In [16]:
m=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
m


array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [17]:
print(m.shape)

(3, 3, 2)


In [39]:
print(m[1:,-2:,0])

[[ 1  5]
 [ 9 13]]


In [47]:
print(m[:,2:,:2])

[[[  7  71]]

 [[  5  51]]

 [[ 13 131]]]


In [48]:
print(c+5)

[[ 8 13  9]
 [14  8 10]
 [16 20 22]
 [24 36 13]]


In [82]:
a=np.array([3.5,3,5,4])
print(a)
a.dtype

[3.5 3.  5.  4. ]


dtype('float64')

In [83]:
a.astype('uint16')     #To change datatype

array([3, 3, 5, 4], dtype=uint16)

In [86]:
c.mean()
c.mean(axis=1)

array([ 5.        ,  5.66666667, 14.33333333, 19.33333333])

In [87]:
c.std(axis=1)

array([2.1602469 , 2.49443826, 2.49443826, 9.39266854])

In [ ]:
#nutsell
# we create array
#1. np.array  2.np.zeros  3.np.arrange  4. np.ones   5. np.random  

In [88]:
np.linspace(1,11,1)

array([1.])

In [91]:
np.random.randint(1,15,[3,4])

array([[ 2,  3, 10, 11],
       [ 2,  9,  5,  2],
       [ 5,  3,  4,  6]])